Apple old site from internet archieve
dipbazz/building-with-backgrounds-and-gradients pull request #1
Opened 2020-09-28 15:01 UTC by dipbazz

## Definition

We have used several techniques like flexbox, position, float, and gradient to layout our and style our website. And it's about apple's iPhone 5 from apple's old website in archives.

## About the Project

This project is about building apple's old website from the archives while making use of flex, positioning, and gradients.

The features of this project are listed below:
1. Website has a header containing:
    - Navbar With  apple logo, menu links, input search
      - Navbar has a linear gradient
    - Background image
    - banner links
2. Has a gallery
    - Images of apple products
    - The gallery items are links
3. Footer section with two main parts
    - The top footer
      - The top footer contains sales links and useful site links
    - The bottom footer
      - The bottom footer contains terms, policy, and rights

2020-09-28 15:59 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! Great work on the apple clone!!

:100: Great README!
:100: Descriptive Pull Request message.
:100: Descriptive enough commit messages.
:100: Updated license with Author and Year.
:100: Great looking website.

### [Mandatory] :red_circle: 

- [x] Use more appropriate HTML tags for navbar's structure. While ```<span>``` works, is not the correct approach when creating a navbar. Please use an unordered list as the project does with the footer menu. See comments.

- [ ] All image tags should have an alternate text. Please don't leave it blank.

- [x] Links in nav are using a unnecessary ```<span>``` wrapper. Please remove it. See inline comment

### [Comments] :green_circle: 

- The <span> tag is an inline container used to mark up a part of a text, or a part of a document. Example.
```<p>My mother has <span style="color:blue">blue</span> eyes.</p>```

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-28 16:03 UTC, jubaan requested changes

2020-09-28 16:03 UTC, jubaan commented on index.html
> +          <span>Store</span>
This ```<span>``` wrapper is unnecessary. This applies to the other elements that match this pattern in the navbar. Except for the apple, and search icon that uses iconify syntax.

2020-09-28 16:03 UTC, jubaan commented on index.html
> +          <img src="images/what.png" alt="" >
Images are missing alternative text. Please fill it with the appropriate information.

2020-09-29 08:18 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-29 08:28 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Misori-simon and @dipbazz 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes 👇.
- [x] Add Mac in navbar
- [ ] Text is missing, Replace image with text and manage it
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-29 08:28 UTC, umairarshadbutt commented on index.html
> +          <img src="images/what.png" alt="what will your verese be" >
Text is missing, Replace image with text and manage it

2020-09-29 08:28 UTC, umairarshadbutt commented on index.html
> +          <img src="images/everyone.png" alt="everyone has something to share, see how people are using ipad in thier unique ways to add to the world story" >
Text is missing, Replace image with text and manage it

2020-09-29 08:28 UTC, umairarshadbutt commented on index.html
> +          <img src="images/watch.png" alt="watch the your verse film and explore the stories" >
Text is missing, Replace image with text and manage it

2020-09-29 09:19 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-29 09:22 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://dipbazz.github.io/building-with-backgrounds-and-gradients/) shows a good understanding of Backgrounds and Gradients. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Misori-simon and @dipbazz! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-29 09:30 UTC, merged